config: Add back simnet.
decred/vspd pull request #419
Opened 2023-08-31 04:49 UTC by JoeGruffins

closes #418

2023-08-31 07:33 UTC, jholdstock requested changes
Apologies! I should have consulted. I had never heard anyone mention vspd on simnet and never seen any code which uses it. Could you share more about how/why you're using it?

2023-08-31 08:26 UTC, JoeGruffins commented
Be in a bash enviroment, probably linux. Have tmux, dcrd, dcrwallet, and vspd in path. Get dcrdex master or better yet https://github.com/decred/dcrdex/pull/2482. go to /dex/testing/dcr and run ./harness. press ctrl + b then p to see the vspd running on simnet. We are using it to test ticket purchasing which is being added. It is working with the UI in that pr and looks quite nice.

2023-08-31 08:32 UTC, JoeGruffins commented
adding to and fixing the params https://github.com/decred/vspd/compare/f8fa4e838d99f03e5b9bb9f4f557909f6eedf42e..b04d3d44616dd0b451004fbdb192bb0819a8dd0b

2023-08-31 08:33 UTC, JoeGruffins commented on cmd/vspd/params.go
> +var simNetParams = netParams{
done!

2023-08-31 08:33 UTC, JoeGruffins commented on cmd/vspd/params.go
> +	minWallets:          1,
done!

2023-09-04 14:55 UTC, davecgh approved these changes

2023-09-04 15:04 UTC, jholdstock approved these changes

2023-09-04 15:51 UTC, merged